nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.1.cjs

npmScopes:
  plentymarkets:
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmAuthToken: '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'
